name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # change if needed

      # 3. Ensure lockfile exists and install dependencies
      - name: Generate lockfile if missing
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json found. Generating..."
            npm install --package-lock-only
          fi

      # 4. Clean install with npm ci
      - name: Install dependencies
        run: npm ci

      # 5. Build the project
      - name: Build project
        run: npm run build

      # 6. Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAFE_DRIVE_00 }}
          channelId: live
          projectId: safe-drive-00
