name: Firebase Deploy

on:
  push:
    branches:
      - main # Deploy only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install Firebase CLI
      - run: npm install -g firebase-tools

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v1.2.0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          projectId: "safe-drive-00" # replace with your Firebase project ID
          channelId: "live"
